### ISSUE TITLE
NullPointException with subLearner.setTreeWeight running gradient boosting

### ISSUE THREAD

**Issue by bryan-woods** [yasserg/jforests#6]
Can someone provide a sample config file for gradient boosting? or better yet a test set that works?

I’ve been trying to run gradient boosting and think that either:
1) I don’t have it configured properly, or
2) there is a bug

I keep getting the following error:

Finished loading datasets.
java.lang.NullPointerException
	at edu.uci.jforests.learning.boosting.GradientBoosting.learn(GradientBoosting.java:105)
	at edu.uci.jforests.applications.ClassificationApp.run(ClassificationApp.java:244)
	at edu.uci.jforests.applications.Runner.train(Runner.java:103)
	at edu.uci.jforests.applications.Runner.main(Runner.java:222)

The error seems to be from trying to set the tree weight with a null.

**Comment by cmacdonald** [comment]
Gradient Boosting is a meta-learner, i.e. it wraps another learner. What is the learner you are trying to apply gradient boosting to?
